
version: "3"

services:
  cashier:
    image: spring-cashier
    depends_on:
    - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 9090
    environment:
      API_KEY: "2H3fONTa8ugl1IcVS7CjLPnPIS2Hp9dJ"      
      API_HOST: "kong:8000/api"
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASS: "cmpe172"
      MYSQL_SCHEMA: "starbucks" 
    restart: always 
  kong:
    image: kong:2.4.0
    platform: linux/amd64
    depends_on:
    - starbucks-service    
    networks:
      - network     
    restart: always  
    ports:
    - "80:8000"
    - "443:8443"
    - "8001:8001"
    - "8444:8444"
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  mysql:
    image: mysql:8.0
    volumes:
      - /tmp:/tmp
    networks:
      - network  
    ports:
      - 3306    
    environment:
      MYSQL_ROOT_PASSWORD: "cmpe172"
    restart: always     
  starbucks:
    image: spring-starbucks-api
    depends_on:
    - mysql    
    volumes:
      - /tmp:/tmp
    networks:
      - network 
    ports:
      - 8080
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASS: "cmpe172"
      MYSQL_SCHEMA: "starbucks"
    restart: always     
  starbucks-service:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - starbucks
    ports:
      - "90:5000"
      - "1936:1936"
    environment:
      HTTPCHK: "GET /ping"
      BACKENDS: "starbucks"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network
  cashier-service:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - cashier
    ports:
      - "91:5000"
      - "1937:1936"
    environment:
      HTTPCHK: "GET /ping"
      BACKENDS: "cashier"
      BACKENDS_PORT: "9090"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

